### ISSUE TITLE
parse_files.py line 124 causes invalid syntax on both windows and linux

### ISSUE THREAD

**Issue by fractaldna22** [rahulremanan/GRUV#1]
Traceback (most recent call last):
  File "convert_directory.py", line 1, in <module>
    from data_utils.parse_files import *
  File "/content/GRUV/data_utils/parse_files.py", line 124
    print 'Processing: ', (file_idx+1),'/',num_files
                       ^
SyntaxError: invalid syntax

**Comment by fractaldna22** [comment]
If i put all prints into parentheses like print('Processing: ', (file_idx+1),'/',num_files) it stops giving me that error and produces a new error: name 'xrange' is not defined"

```
Traceback (most recent call last):
  File "convert_directory.py", line 13, in <module>
    new_directory = convert_folder_to_wav(input_directory, freq)
  File "/content/GRUV/data_utils/parse_files.py", line 59, in convert_folder_to_wav
    convert_mp3_to_wav(filename=fullfilename, sample_frequency=sample_rate)
  File "/content/GRUV/data_utils/parse_files.py", line 17, in convert_mp3_to_wav
    for i in xrange(len(files)-1):
NameError: name 'xrange' is not defined
```
